### ISSUE TITLE
Add no-cache rule to html header

### ISSUE THREAD

**Issue by hdznrrd** [cccs/eh14-infopage#13]

**Comment by rashfael** [comment]
Caching rules should be set by using HTTP headers.

**Comment by hdznrrd** [comment]
whatever works ;) i just had to explicitly press f5 everyone i wanted to see a change, that's not really nice

**Comment by Skyr** [comment]
Apache config modified:

```
Cache-Control: max-age=7200, must-revalidate
```

Page should be automatically reloaded after 2h
