### ISSUE TITLE
Add IRC channel to info page

### ISSUE THREAD

**Issue by momorientes** [cccs/eh14-infopage#16]

**Comment by rixx** [comment]
Or the contact page (too), maybe?

**Comment by hdznrrd** [comment]
why not both? :+1:

**Comment by hdznrrd** [comment]
however, it should be clear that "official inquiries" should be mailed to eh2014-orga@cccs.de if one wants to be sure to get an answer from the source ;)

**Comment by momorientes** [comment]
+1 for both, including hdznrrds disclaimer
